### ISSUE TITLE
bijwerken naar 2.20

### ISSUE THREAD

**Issue by jknockaert** [OpenTaal/opentaal-hunspell#1]
Kunnen de bestanden in de download map bijgewerkt worden naar versie 2.20? Zie bv. https://github.com/OpenTaal/opentaal-hunspell/blob/5fb9d380f21433a31d5c9ae96d7189ff92e9a876/downloads/nl.aff#L5

**Comment by PanderMusubi** [comment]
Deze bestanden zijn nog volop in ontwikkeling en moet je nog niet gebruiken. Als het af is komt er hier een release.

**Comment by jknockaert** [comment]
@PanderMusubi Dank voor de reactie. Zijn de huidige 2.10G bestanden in de downloads map bruikbaar? Het is nu enigszins verwarrend: op https://www.opentaal.org/ lijkt het alsof versie 2.2 af is, en op https://www.opentaal.org/bestanden staan bestanden voor versies 2.0 en 2.1 door elkaar...

**Comment by PanderMusubi** [comment]
De [woordenlijst](https://github.com/opentaal/opentaal-wordlist) is af, de spellingcontrole nog niet. Dat zijn twee verschillende zaken. Ik zal voor de repo hier een waarschuwing erbij zetten.

**Comment by kad-michij** [comment]
Weten jullie alternatieven voor een Nederlandse spelling checker? We willen voor groot aantal OCR-bestanden controleren of de gevonden woorden voorkomen in de Nederlandse taal. Hebben jullie hier ideeën voor?

**Comment by PanderMusubi** [comment]
Ja, Hunspell of Nuspell (ook nog even wachten voor optimalisatie suggesties voor NL) met onze aankomende nieuwe spellingcontrole. Nog een paar weken geduld. Anders Hunspell met onze spellingcontrole versie 2.10G

**Comment by PanderMusubi** [comment]
Zie https://github.com/OpenTaal/opentaal-hunspell/releases voor versie 2.20.18
