### ISSUE TITLE
What are the preferred letters to be used in dutch language: "i j" vs. "ĳ"

### ISSUE THREAD

**Issue by PAX523** [OpenTaal/opentaal-hunspell#13]
(I'm no native speaker for dutch - I know almost nothing about this language)

Only one general question about `ICONV` and `OCONV`. Did I understand the hunspell code sources correctly? 

In input words which must be spell-checked the characters `i j` will be replaced by the single character `ĳ`.

In contrast to that, for typo correction suggestions the single `ĳ` letter gets replaced by `i j`.

Do you prefer the two letters instead of the single letter if you write texts? When will the single letter be used?

**Comment by PanderMusubi** [comment]
In texts, use an `i` and an `j` for a word such as `zijn` (to be). Only inside the spelling checker files for Dutch, we use the `ĳ` ligature but that concerns only dictionary development.
