### ISSUE TITLE
Taalhaperingen in de "Beschrijving van de overige bestanden"

### ISSUE THREAD

**Issue by druud** [OpenTaal/opentaal-hunspell#2]
> Beschrijving van de overige bestanden is:
> 
>     elements/archaic.tsv (archaïsch), deze woorden zijn die nog wel gebruikt worden, alle zitten in de woordenlijst

"deze woorden zijn die"?

>     elements/excluded.tsv, deze woorden moeten worden uitgesloten van de spellingcontrole omdat ze verwarrend zijn met een ander woord dat ook correct is en in de meeste gevallen bedoeld is

"verwarrend zijn met"?

>     elements/inflections.tsv, zijn flexies met hun basiswoorden (soms zijn dat er meerdere) en een flexie kan zelf ook een basiswoord zijn voor een andere flexie als suggestie gegeven worden

"voor een andere flexie als suggestie gegeven worden"?

>     elements/nosuggest.txt, deze woorden mogen niet als suggestie gegeven worden
>     elements/objectionable.txt (verwerpelijk), deze woorden zijn verwerpelijk omdat ze (buiten de studie naar dit woord) ze als discriminerend of rasistisch worden ervaren

"ze (...) ze"?
"rasistisch"?

>     elements/obsolete.tsv (ongebruik), deze woorden zijn in ongebruik geraakt, sommige zitten nog in de woordenlijst (weeuw), sommige niet meer (arre) en sommige zijn fout omdat er een andere spelling van is (pannekoek) of een ander woord voor is plaats is gekomen (chocozoen)

"of een ander woord voor is plaats is gekomen"?

-- Ruud

**Comment by PanderMusubi** [comment]
Gefikst in https://github.com/OpenTaal/opentaal-hunspell/commit/8388c767e8d94b5db7334f91c491b656b5147447
